fix(M): checked data population in pre commit hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -14,7 +14,7 @@ uv run pre-commit run --config .pre-commit-config.yaml --hook-stage pre-commit
 
 echo "✅- Linting and formatting checks passed"
 
-
+# Run alembic checks
 if git diff --cached --name-only | grep -qE "(models\.py|models/|alembic/versions/)"; then
     echo "🗃️- Checking database migrations and models..."
 
@@ -61,9 +61,19 @@ if git diff --cached --name-only | grep -qE "(models\.py|models/|alembic/version
         exit 1
     fi
 
+    # Ensure that data population still works with the new schema
+    echo "💾- Initializing database with seed data..."
+    if ! docker compose up --abort-on-container-exit --exit-code-from init-db init-db; then
+    echo "❌- Database initialization failed."
+    exit 1
+    fi
+    echo "✅- Database initialization succeeded."
+
     echo "✅ Checks for database migrations and models passed"
 else
     echo "ℹ️- No model or migration changes detected, skipping database checks."
 fi
 
+
 exit 0
+
