remove special characters from test-migrations.sh

diff --git a/.github/workflows/check-migrations-on-pr.yml b/.github/workflows/check-migrations-on-pr.yml
--- a/.github/workflows/check-migrations-on-pr.yml
+++ b/.github/workflows/check-migrations-on-pr.yml
@@ -105,5 +105,11 @@ jobs:
           CID=$(docker compose -f docker-compose.yml -f .husky/docker-compose.ci.yml run --build --no-deps -d test-migrations | tail -n1)
           docker logs -f "$CID"
           EXIT=$(docker wait "$CID")
+          if [[ "$EXIT" -eq 0 ]]; then
+            echo "✅- Migration checks passed"
+          else
+            echo "❌- Migration checks failed"
+            exit 1
+          fi
       - name: Dummy run after migrations
         run: echo "No syntax error!"
